<h1>Categories</h1>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created</th>
        <th>Action</th>
    </tr>
    <?php foreach ($this->categories as $key => $category): ?>
    <tr>
        <td>
          <?php echo $category->cat_id?>
        </td>
        <td>
                <?php echo $category->cat_name ?>
            </a>
        </td>
        <td>
            <?php echo $category->cat_created_at ?>
        </td>

        <td>
            <?php echo $category->cat_updated_at ?>
        </td>
        <td>
            <a href="<?php echo $this->baseUrl('/categories/edit/id/' . $category->cat_id) ?>">Edit</a>
            <a href="<?php echo $this->baseUrl('/categories/del/id/' . $category->cat_id) ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach ?>
</table>